- hosts: master
  become: yes
  tasks:
    - name: Start the cluster
      shell: kubeadm init --pod-network-cidr=192.168.0.0/16 --apiserver-advertise-address=192.168.2.49
      args:
        chdir: $HOME
        

    - name: create .kube directory
      become: yes
      become_user: ubuntu
      file:
        path: $HOME/.kube
        state: directory
        mode: 0755

    - name: copy admin.conf to user's kube config
      become: yes
      become_user: root
      copy:
        src: /etc/kubernetes/admin.conf
        dest: /home/ubuntu/.kube/config
        remote_src: yes
        owner: ubuntu

    - name: changing ownership 
      become: yes
      become_user: ubuntu
      shell: chown ubuntu:ubuntu $HOME/.kube/config

    - name: install Pod network
      become: yes
      become_user: root
      shell: kubectl apply -f  https://git.io/weave-kube-1.6
      args:
        chdir: $HOME
        
      environment:
        KUBECONFIG: "/etc/kubernetes/admin.conf"
      when: inventory_hostname in (groups['masters'] | last)
